on: [push]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed directories
        id: set-matrix
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^.*\/' | awk -F/ '{print $1}' | sort -u)
          DIRS=()
          for DIR in $CHANGED_DIRS; do
            if [[ "$DIR" == "al" || "$DIR" == "jn" || "$DIR" == "tf" || "$DIR" == "sa" ]]; then
              DIRS+=("$DIR")
            fi
          done
          if [ ${#DIRS[@]} -eq 0 ]; then
            DIRS+=("none")  # Default or placeholder directory
          fi
          JSON_ARRAY=$(printf '%s\n' "${DIRS[@]}" | jq -R . | jq -s .)
          echo "::set-output name=matrix::{\"dir\": $JSON_ARRAY}"

  publish:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.changes.outputs.matrix)}}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish to Cloudflare Pages
        if: matrix.dir != 'none'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: YOUR_ACCOUNT_ID
          projectName: "${{ matrix.dir }}-1"
          directory: "${{ matrix.dir }}"
          branch: main

